model_list:
  - model_name: bedrock-claude-sonnect
    litellm_params:
      model: bedrock
      api_base: xxx

general_settings:
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Id
      litellm_user_role: internal_user
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer
      